services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped

    ports:
      - "127.0.0.1:27017:27017"

    env_file:
      - .env

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

    networks:
      - archiver-net

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
  mongo_config:

networks:
  archiver-net:
    external: true