services:
  channel-archiver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faraz-channel-archiver
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./session_data:/data
    networks:
      - archiver-net

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: faraz-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - archiver-net

networks:
  archiver-net:
    external: true