"""Pydantic v2 document models for all MongoDB collections."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Annotated, Any, Literal

from bson import ObjectId
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_serializer


# ── ObjectId helper ───────────────────────────────────────────────────────────

class PyObjectId(str):
    """A string subclass that validates and serialises MongoDB ObjectIds."""

    @classmethod
    def __get_validators__(cls):  # pydantic v1 compat shim
        yield cls.validate

    @classmethod
    def validate(cls, v: Any) -> "PyObjectId":
        if isinstance(v, ObjectId):
            return cls(str(v))
        if isinstance(v, cls):
            return v
        if isinstance(v, str) and ObjectId.is_valid(v):
            return cls(v)
        raise ValueError(f"Invalid ObjectId: {v!r}")

    @classmethod
    def __get_pydantic_core_schema__(cls, source_type: Any, handler: Any):  # noqa: ANN001
        from pydantic_core import core_schema

        return core_schema.no_info_plain_validator_function(
            cls.validate,
            serialization=core_schema.to_string_ser_schema(),
        )


# Annotated alias used in Field definitions
ObjId = Annotated[PyObjectId, Field(default_factory=lambda: PyObjectId(str(ObjectId())))]


# ── Embedded sub-documents ────────────────────────────────────────────────────

class FileIds(BaseModel):
    """Stores Telegram file_id values for each media type in a forwarded message."""

    model_config = ConfigDict(populate_by_name=True)

    photo: list[str] = Field(default_factory=list)
    video: list[str] = Field(default_factory=list)
    document: list[str] = Field(default_factory=list)
    audio: list[str] = Field(default_factory=list)
    animation: list[str] = Field(default_factory=list)


class MediaItem(BaseModel):
    """One selectable media piece attached to a NewsItem."""

    model_config = ConfigDict(populate_by_name=True)

    media_type: Literal["photo", "video", "document", "audio", "animation"] = Field(
        ..., description="Telegram media type"
    )
    file_id: str = Field(..., description="Telegram file_id")
    caption: str | None = Field(default=None, description="Optional caption override")
    selected: bool = Field(default=True, description="Whether this media is selected for publishing")


class PublicationResult(BaseModel):
    """Result of publishing a NewsItem to one destination channel."""

    model_config = ConfigDict(populate_by_name=True)

    channel_id: str = Field(..., description="Destination channel ID")
    message_id: int | None = Field(
        default=None,
        description="Published message ID in channel",
    )
    published_at: datetime | None = Field(default=None)
    published_by: int | None = Field(
        default=None,
        description="Telegram ID of the admin who published the news",
    )
    success: bool = Field(default=False)
    error: str | None = Field(
        default=None,
        description="Error message if publishing failed",
    )

    
# ── Primary collection documents ──────────────────────────────────────────────

class FetchedMessage(BaseModel):
    """Document in the ``fetched_messages`` collection.

    Represents a raw message forwarded from a source channel into the private
    intermediary channel.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(default_factory=lambda: PyObjectId(str(ObjectId())), alias="_id")

    # Source identifiers
    source_chat_id: int = Field(..., description="Telegram chat ID of the source channel")
    source_msg_id: int = Field(..., description="Message ID in the source channel")

    # Bot-side identifiers (set after forwarding)
    last_bot_msg_id: int | None = Field(
        default=None, description="Most recent message ID posted by the bot in the private channel"
    )
    bot_text: str | None = Field(default=None, description="Text extracted / generated by the bot")

    file_ids: FileIds = Field(default_factory=FileIds)

    state: Literal[
        "fetched",
        "processing",
        "pending_review",
        "approved",
        "rejected",
        "published",
        "error",
    ] = Field(default="fetched")

    fetched_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class NewsItem(BaseModel):
    """Document in the ``news_items`` collection.

    Central workflow document that tracks a news piece from ingestion through
    AI processing, admin review, and final publication.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(default_factory=lambda: PyObjectId(str(ObjectId())), alias="_id")

    # Traceability back to the raw source
    source_chat_id: int = Field(..., description="Originating channel chat ID")
    source_msg_id: int = Field(..., description="Original message ID in the source channel")
    fetched_message_id: PyObjectId | None = Field(
        default=None, description="Reference to FetchedMessage._id"
    )

    # Content
    original_text: str | None = Field(default=None, description="Raw text from source message")
    processed_text: str | None = Field(default=None, description="AI-processed text")
    final_text: str | None = Field(default=None, description="Admin-approved final text")

    media: list[MediaItem] = Field(default_factory=list)

    # Workflow state
    state: Literal[
        "new",
        "ai_processing",
        "pending_review",
        "approved",
        "rejected",
        "publishing",
        "published",
        "error",
    ] = Field(default="new")

    # Admin tracking
    review_msg_id: int | None = Field(
        default=None, description="Message ID of the review post in the admin group"
    )
    reviewed_by: int | None = Field(default=None, description="Telegram ID of reviewing admin")
    reviewed_at: datetime | None = Field(default=None)
    rejection_reason: str | None = Field(default=None)

    # Publication
    publications: list[PublicationResult] = Field(default_factory=list)

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AdminUser(BaseModel):
    """Document in the ``admin_users`` collection."""

    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(default_factory=lambda: PyObjectId(str(ObjectId())), alias="_id")

    telegram_id: int = Field(..., description="Telegram user ID")
    username: str | None = Field(default=None, description="Telegram @username (without @)")
    role: Literal["admin", "supervisor"] = Field(
        default="admin",
        description="'admin' can manage content; 'supervisor' has full control",
    )
    added_by: int | None = Field(
        default=None, description="Telegram ID of the user who added this admin"
    )
    added_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_active: bool = Field(default=True)


class ChannelHistory(BaseModel):
    """An audit event for channel."""

    action: Literal["added", "removed"]
    performed_by: int = Field(
        ...,
        description="Telegram ID of the admin who performed the action",
    )
    performed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class SourceChannel(BaseModel):
    """Document in the ``source_channels`` collection."""

    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(default_factory=lambda: PyObjectId(str(ObjectId())), alias="_id")

    channel_id: str = Field(..., description="Telegram channel ID (string form)")
    channel_username: str | None = Field(default=None, description="@username without the @")
    title: str | None = Field(default=None, description="Display title of the channel")
    added_by: int = Field(..., description="Telegram ID of the admin who added this channel")
    added_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_active: bool = Field(default=True)

    # Validation
    validation_status: str = Field(
        default="pending",
        description="Current validation state of the source channel",
    )


class DestinationChannel(BaseModel):
    """Document in the ``destination_channels`` collection."""

    model_config = ConfigDict(populate_by_name=True)

    # MongoDB
    id: PyObjectId = Field(
        default_factory=lambda: PyObjectId(str(ObjectId())),
        alias="_id",
    )

    # Telegram identity
    channel_id: str = Field(
        ...,
        description="Telegram channel ID (string form)",
    )
    channel_username: str | None = Field(
        default=None,
        description="@username without the @",
    )
    title: str | None = Field(
        default=None,
        description="Display title of the channel",
    )

    # Bot access
    bot_status: str | None = Field(
        default=None,
        description="Current bot membership status in the channel",
    )
    is_bot_member: bool = Field(
        default=False,
        description="Whether the bot is a member of the channel",
    )
    is_bot_admin: bool = Field(
        default=False,
        description="Whether the bot is an administrator of the channel",
    )
    can_post_messages: bool = Field(
        default=False,
        description="Whether the bot can post messages in the channel",
    )

    # Validation
    validation_status: str = Field(
        default="invalid",
        description="Whether the destination channel is currently valid",
    )

    # Application state
    is_active: bool = Field(
        default=True,
        description="Whether NewsHub should publish to this channel",
    )

    # History
    history: list[ChannelHistory] = Field(
        default_factory=list,
        description="Audit history of changes made to this destination channel",
    )


class AIPrompt(BaseModel):
    """Document in the ``ai_prompts`` collection.

    Stores the system / user prompt text for each AI operation so that admins
    can update them at runtime without redeploying.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: PyObjectId = Field(default_factory=lambda: PyObjectId(str(ObjectId())), alias="_id")

    operation: Literal["shorten", "expand", "clean"] = Field(
        ..., description="The AI operation this prompt is used for"
    )
    prompt_text: str = Field(..., description="The full prompt template sent to the model")
    updated_by: int = Field(..., description="Telegram ID of the admin who last updated the prompt")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
